name: Sky Betting & Gaming Technology
title: Sky Betting & Gaming Technology
markdown: kramdown
url: https://technology.skybettingandgaming.com
host: 0.0.0.0
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-feed
    - jekyll-paginate
paginate: 10
paginate_path: "/:num/"
kramdown:
    input: GFM
    syntax_highlighter: rouge
exclude: ['vendor', 'node_modules', 'spec']
